export const userConstants = {
  LOGIN_REQUEST: "USERS_LOGIN_REQUEST",
  LOGIN_SUCCESS: "USERS_LOGIN_SUCCESS",
  LOGIN_FAILURE: "USERS_LOGIN_FAILURE",
  LOGOUT_REQUEST: "USER_LOGOUT_REQUEST",
  REGISTER_REQUEST: "USERS_REGISTER_REQUEST",
  REGISTER_SUCCESS: "USERS_REGISTER_SUCCESS",
  REGISTER_FAILURE: "USERS_REGISTER_FAILURE",
};

export const recipeConstants = {
  RECIPE_REQUEST: "RECIPE_REQUEST",
  RECIPE_REQUEST_SUCCESS: "RECIPE_REQUEST_SUCCESS",
  RECIPE_REQUEST_FAILURE: "RECIPE_REQUEST_FAILURE",
  RECIPE_DETAIL_REQUEST: "RECIPE_DETAIL_REQUEST",
  RECIPE_DETAIL_REQUEST_SUCCESS: "RECIPE_DETAIL_REQUEST_SUCCESS",
  RECIPE_DETAIL_REQUEST_FAILURE: "RECIPE_DETAIL_REQUEST_FAILURE",
};
